[package]
name = "actor"
version = "0.1.0"
authors = ["David Beck <david.beck.priv@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/dbeck/actor_rs"
description = "This is an experimental actor model."
keywords = ["actor", "concurrency"]
readme = "README.md"
homepage = "https://github.com/dbeck/actor_rs"
#documentation = "..."

[dependencies]
lossyq = "0.1.5"
